apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-alexnet-cpu-A
spec:
  containers:
  - name: tensorflow-alexnet-cpu
    image: swiftdiaries/bench
    command:
    - "/bin/bash"
    - "-c"
    - "python tf_cnn_benchmarks.py --device=cpu --model=alexnet --data_format=NHWC --batch_size=32"  
    resources:
      requests:
        cpu: 23
        memory: "32Gi"
        alpha.kubernetes.io/nvidia-gpu: 1
      limits:
        cpu: 23
        alpha.kubernetes.io/nvidia-gpu: 1
        memory: "32Gi"
    volumeMounts:
    - name: nvidia-driver-375-82
      mountPath: /usr/local/nvidia
      readOnly: true
    - name: libcuda-so
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-375-82
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.375.82
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: nvidia-driver-375-82
    hostPath:
      path: /usr/lib/nvidia-375
  - name: libcuda-so
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so
  - name: libcuda-so-1
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - name: libcuda-so-375-82
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.375.82
