apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-vgg16-cpu14
spec:
  containers:
  - name: tensorflow-vgg16-cpu
    image: swiftdiaries/bench
    command:
    - "/bin/bash"
    - "-c"
    - "python tf_cnn_benchmarks.py --device=cpu --model=vgg16 --data_format=NHWC --batch_size=16 --num_intra_threads=14"  
    resources:
      requests:
        alpha.kubernetes.io/nvidia-gpu: 1
        cpu: 14
        memory: 16Gi
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
        cpu: 14
        memory: 16Gi
    volumeMounts:
    - name: nvidia-driver-375-82
      mountPath: /usr/local/nvidia
      readOnly: true
    - name: libcuda-so
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-375-82
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.375.82
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: nvidia-driver-375-82
    hostPath:
      path: /usr/lib/nvidia-375
  - name: libcuda-so
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so
  - name: libcuda-so-1
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - name: libcuda-so-375-82
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.375.82
    
