apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-rnn-cpu
spec:
  containers:
  - name: tensorflow-rnn-cpu
    image: swiftdiaries/bench
    command:
    - "/bin/bash"
    - "-c"
    - "python train.py --data_file=data/sherlock/input.txt"  
    resources:
      requests:
        alpha.kubernetes.io/nvidia-gpu: 1
        cpu: 40
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
        cpu: 40
    volumeMounts:
    - name: nvidia-driver-375-82
      mountPath: /usr/local/nvidia
      readOnly: true
    - name: libcuda-so
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-375-82
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.375.82
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: nvidia-driver-375-82
    hostPath:
      path: /usr/lib/nvidia-375
  - name: libcuda-so
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so
  - name: libcuda-so-1
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - name: libcuda-so-375-82
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.375.82
    
